install.packages("twitteR")
library(twitteR)
install.packages("ROAuth")
library("ROAuth")
install.packages("httr")
library(httr)
install.packages("base64enc")
library(base64enc)
install.packages("tm")
library(tm)
install.packages("coda")
library(coda)
install.packages("mvtnorm")
library(mvtnorm)
install.packages("wordcloud")
library(wordcloud)
install.packages("e1071")
library(e1071)
install.packages("randomForest")
library(randomForest)



